name: Docker Image CI

on:
  push:
    branches: [ "k8s" ]
  pull_request:
    branches: [ "k8s" ]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Login to ACR virtual human
        uses: docker/login-action@v3
        with:
          registry: vhregistry.azurecr.io
          username: ${{ vars.ACR_USERNAME }}
          password: ${{ secrets.ACR_TOKEN }} 
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3          
      - uses: actions/checkout@v4
      # - name: Build the Docker image
      #   run: docker build  --file convai_narrative_memory_poc/workers/indexer/Dockerfile --tag vhregistry.azurecr.io/narmem-indexer:$(date +%s)
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: convai_narrative_memory_poc/workers/indexer/
          push: true
          tags: vhregistry.azurecr.io/narmem-indexer:$(date +%s)